name: "picard_collectrnaseqmetrics"
## TODO nf-core: Add a description of the module and list keywords
description: Collect metrics from a RNAseq BAM file
keywords:
  - rna
  - bam
  - metrics
  - alignment
  - statistics
  - quality
tools:
  - "picard":
      ## TODO nf-core: Add a description and other details for the software below
      description: "Java tools for working with NGS data in the BAM format"
      homepage: "None"
      documentation: "None"
      tool_dev_url: "https://github.com/broadinstitute/picard"
      doi: ""
      licence: "['MIT']"

## TODO nf-core: Add a description of all of the variables used as input
input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false, strandedness:true ]
  #
  ## TODO nf-core: Delete / customise this example input
  - bam:
      type: file
      description: BAM/SAM file
      pattern: "*.{bam,sam}"
  - fasta:
      type: file
      description: Genome fasta file
  - ref_flat:
      type: file
      description: Genome ref_flat file
  - rrna_intervals:
      type: file
      description: Interval file of ribosomal RNA regions

## TODO nf-core: Add a description of all of the variables used as output
output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - metrics:
      type: file
      description: RNA alignment metrics files generated by picard
      pattern: "*.rna_metrics"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@anoronh4"
