name: "portcullis_full"
description: Run all Portcullis steps in one go
keywords:
  - rnaseq
  - genome
  - splice
  - junction
tools:
  - "portcullis":
      description: "Portcullis is a tool that filters out invalid splice junctions from
        RNA-seq alignment data. It accepts BAM files from various RNA-seq mappers, analyzes
        splice junctions and removes likely false positives, outputting filtered results
        in multiple formats for downstream analysis."
      homepage: "https://portcullis.readthedocs.io/en/latest/index.html"
      documentation: "https://portcullis.readthedocs.io/en/latest/using.html"
      doi: "10.1101/217620"
      license: ["GPL-3.0"]
      identifier: biotools:portcullis
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing information about the sample
          e.g. [ id:'sample1', single_end:false ]
    - bam:
        type: file
        description: RNA-seq-aligned and sorted BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
        ontologies:
          - edam: "http://edamontology.org/format_2572"
          - edam: "http://edamontology.org/format_2573"
          - edam: "http://edamontology.org/format_3462"
  - - meta2:
        type: map
        description: |
          Groovy Map containing information about the sample
          e.g. [ id:'sample1', single_end:false ]
    - bed:
        type: file
        description: Input reference annotation of junctions in BED format
        pattern: "*.bed"
        ontologies:
          - edam: "http://edamontology.org/format_3003"
  - - meta3:
        type: map
        description: |
          Groovy Map containing information about the sample
          e.g. [ id:'sample1', single_end:false ]
    - fasta:
        type: file
        description: Input genome reference fasta file
        pattern: "*.{fa,fasta}"
        ontologies:
          - edam: "http://edamontology.org/format_1332"
output:
  - log:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.log"
          ontologies: &id001
            - edam: "http://edamontology.org/format_2330"
      - "*.log":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.log"
          ontologies: *id001
  - pass_junctions_bed:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.pass.junctions.bed"
          ontologies: &id002
            - edam: "http://edamontology.org/format_3003"
      - "*.pass.junctions.bed":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.pass.junctions.bed"
          ontologies: *id002
  - bed:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.bed"
          ontologies: &id003
            - edam: "http://edamontology.org/format_3003"
      - "*.bed":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.bed"
          ontologies: *id003
  - pass_junctions_tab:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.pass.junctions.tab"
          ontologies: &id004
            - edam: "http://edamontology.org/format_3475"
      - "*.pass.junctions.tab":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.pass.junctions.tab"
          ontologies: *id004
  - tab:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.tab"
          ontologies: &id005
            - edam: "http://edamontology.org/format_3475"
      - "*.tab":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.tab"
          ontologies: *id005
  - intron_gff:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.intron.gff3"
          ontologies: &id006
            - edam: "http://edamontology.org/format_1975"
      - "*.intron.gff3":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.intron.gff3"
          ontologies: *id006
  - exon_gff:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.exon.gff3"
          ontologies: &id007
            - edam: "http://edamontology.org/format_1975"
      - "*.exon.gff3":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.exon.gff3"
          ontologies: *id007
  - spliced_bam:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.bam"
          ontologies: &id008
            - edam: "http://edamontology.org/format_2572"
      - "*.bam":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.bam"
          ontologies: *id008
  - spliced_bai:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.bai"
          ontologies: &id009
            - edam: "http://edamontology.org/format_3327"

      - "*.bai":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.bai"
          ontologies: *id009
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
          ontologies:
            - edam: "http://edamontology.org/format_3750"
authors:
  - "@jblancoheredia"
maintainer:
  - "@jblancoheredia"
  - "@anoronh4"
