name: csvtk_join
description: Join two or more CSV (or TSV) tables by selected fields into a single table
keywords:
  - join
  - tsv
  - csv
tools:
  - csvtk:
      description: A cross-platform, efficient, practical CSV/TSV toolkit
      homepage: http://bioinf.shenwei.me/csvtk
      documentation: http://bioinf.shenwei.me/csvtk
      tool_dev_url: https://github.com/shenwei356/csvtk

      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - csv:
      type: file
      description: CSV/TSV formatted files
      pattern: "*.{csv,tsv}"
  - in_format:
      type: string
      description: Input format (csv, tab, or a delimiting character)
      pattern: "*"
  - out_format:
      type: string
      description: Output format (csv, tab, or a delimiting character)
      pattern: "*"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "version.yml"
  - csv:
      type: file
      description: Joined CSV/TSV file
      pattern: "*.{csv,tsv}"

authors:
  - "@anoronh4"
